language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

#@todo take out this temp workaround
#https://www.ruby-lang.org/en/news/2014/03/29/heap-overflow-in-yaml-uri-escape-parsing-cve-2014-2525/
before_install:
  - rvm get stable

bundler_args: --without integration

before_script:
  - bundle exec berks install

script:
  - bundle exec rake travis

branches:
  only:
    - master

notifications:
  email:
    - dev@escapestudios.com